# Generated by Django 5.2.3 on 2025-06-22 18:27

import autoslug.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models

import videos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                (
                    "media",
                    models.FileField(
                        upload_to="videos/",
                        validators=[
                            videos.validators.NameValidator(),
                            videos.validators.VideoValidator(),
                        ],
                    ),
                ),
                ("search", django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
                "db_table": "videos",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search"], name="videos_search_85529f_gin"
                    )
                ],
            },
        ),
    ]
